name: Run PHP Tests & Static Analysis

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2', '8.3']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP v${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, mbstring
          coverage: xdebug
      - name: Install Composer dependencies
        run: |
          if [[ ${{ matrix.php-version }} < '8.2' ]]; then
            composer update --prefer-dist --no-progress --no-suggest
          else
            composer install --prefer-dist --no-progress --no-suggest
          fi
      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Run static analysis
        if: matrix.php-version == '8.3'
        run: ./vendor/bin/phpstan analyse src tests --level=8
      - name: Check coding style
        if: matrix.php-version == '8.3'
        run: composer cs
